spring:
  social:
    facebook:
      appId: 477872509238452
      appSecret: a24adf0e01bf3ae4607dfa4ab44c175e
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
  jpa:
    database: MYSQL
    show_sql: false
    hibernate:
      ddl-auto: update
      c3p0:
        min_size: 3
        max_size: 10
        timeout: 300
        max_statements: 50
        idle_test_period: 3000
  datasource:
    url: jdbc:mysql://bed8118f1581ec:37bd28cb@us-cdbr-iron-east-03.cleardb.net/heroku_ac5f7d314de0b58?reconnect=true&useUnicode=true&characterEncoding=utf-8
    username: bed8118f1581ec
    password: 37bd28cb
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  session:
    timeout: 3600
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: h3Q1/vEmoZ+QvGb0Ix53wQ
app:
  crypto:
    api-var: ENC(8YMTaYiOC5A/VNjCylqMCyCjy3AggiYjSMv0TAuJNv0=)
    algorithm: AES/ECB/PKCS5Padding
  mail-sender:
    email: djun_igari@hotmail.com
    noreply: noreply@keducation.com
    api-key: ENC(8YMTaYiOC5A/VNjCylqMCyCjy3AggiYjSMv0TAuJNv0=)
  user:
    key:
      activate: 89312
      reset:
        password: 312312