spring:
  social:
    facebook:
      appId: 671968559674761
      appSecret: 07000a1060b7b8688bbf7aeb18623fdb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
  jpa:
    database: MYSQL
    show_sql: false
    hibernate:
      ddl-auto: update
      c3p0:
        min_size: 3
        max_size: 10
        timeout: 300
        max_statements: 50
        idle_test_period: 3000
  datasource:
    url: jdbc:mysql://bed8118f1581ec:37bd28cb@us-cdbr-iron-east-03.cleardb.net/heroku_ac5f7d314de0b58?reconnect=true&useUnicode=true&characterEncoding=utf-8
    username: bed8118f1581ec
    password: 37bd28cb
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  session:
    timeout: 3600