spring:
  social:
    facebook:
      appId: ENC(H45rpEm6yVcg+rFcIKQY68sgpo2ARdd2)
      appSecret: ENC(ke+cd6vYe7qY9daJKApt/4mBh9UIzweH+t780n3MDJsqKmYiJa7zng0qAfnueVt0)
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
  jpa:
    database: MYSQL
    show_sql: false
    hibernate:
      ddl-auto: update
      c3p0:
        min_size: 3
        max_size: 10
        timeout: 300
        max_statements: 50
        idle_test_period: 3000
  datasource:
    url: ${CLEARDB_DATABASE_URL:}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  session:
    timeout: 3600
jasypt:
  encryptor:
    algorithm: ${JASYPT_ENCRYPTOR_ALGORITHM:}
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
app:
  security:
    crypto:
      key_user_id: ENC(UdYSZhA7aPtf9BhNizz0yLKT2zka11kJ)
      key_activate_user: ENC(zZWGUw7V3gzKk1wMBrKk0w==)
      key_reset_password_user: ENC(mkw244IcryYPA9iTCw46hQ==)
    login:
      session.user: user
  sender-mail:
    email: djun_igari@hotmail.com
    noreply-email: noreply@keducation.com
    api-key: ENC(4V1HOOX7rcY1NidY99NqDmXnzEiBgTjymoLPSpgBdMRBzcbHoNCekNGN4h18G6wIqrKC1mYWr6bMUQcNEJii38xqDNNE3m3OicPbSVDEgjg=)
